import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "QuizBrain - Next14 Dynamic quiz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
